services:
  web:
    build: .
    restart: unless-stopped
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.guided-apps.rule=Host(`guided-apps.com`)"
      - "traefik.http.routers.guided-apps.entrypoints=https"
      - "traefik.http.routers.guided-apps.tls=true"
      - "traefik.http.routers.guided-apps.tls.certresolver=letsencrypt"
      - "traefik.http.services.guided-apps.loadbalancer.server.port=80"
      - "traefik.http.routers.guided-apps-http.rule=Host(`guided-apps.com`)"
      - "traefik.http.routers.guided-apps-http.entrypoints=http"
      - "traefik.http.routers.guided-apps-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
